version: "3"

services:
  demo-ecommerce:
    image: bkimminich/juice-shop
    container_name: demo-ecommerce
    # ports:
    #  - 3000
    restart: unless-stopped
    networks:
      internal-nw:

  firewall:
    build: ./online_model/
    container_name: firewall
    ports:
      - 0.0.0.0:8080:8081
    restart: unless-stopped
    volumes:
      - ./online_model/settings.toml:/settings.toml
    networks:
      internal-nw:

networks:
  internal-nw:
