[package]
name = "caching"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
futures = "0.3.30"
moka = { version = "0.12.5", features = ["future", "sync"] }
